### ISSUE TITLE
Ability to disable preview 

### ISSUE THREAD

**Issue by what1s1ove** [KiwiKilian/eleventy-plugin-og-image#253]
Hey! Thanks for such an awesome plugin!

I have some linters like W3C and Linthtml on the Git pre-commit hook. Since the preview folder contains a lot of invalid HTML, I receive errors when committing changes. Of course, I can create a production build and then try to commit, but this takes time, and during development, I want to commit quickly.

I do not want to change my linters' configuration, and I do not use the preview functionality. Therefore, I think it would be better to add an option to disable the creation of the preview folder altogether.

I’m interested to know what you think about this.

**Comment by KiwiKilian** [comment]
I'm just concerned about having to many options to configure, test and maintain. Especially because I don't see the use case, allow me some personal views:
- Linting the Code from `watch`/`serve` isn't the same as `build` (where preview will be removed), from my point of view it would be more common to lint only the `build` artifacts with a HTML linter
- It should be possible to configure a linter to ignore some directory, but I know this can be a hassle with lint-staged

I will think about it.

**Comment by what1s1ove** [comment]
> I'm just concerned about having to many options to configure, test and maintain. Especially because I don't see the use case, allow me some personal views:
> 
> * Linting the Code from `watch`/`serve` isn't the same as `build` (where preview will be removed), from my point of view it would be more common to lint only the `build` artifacts with a HTML linter
> * It should be possible to configure a linter to ignore some directory, but I know this can be a hassle with lint-staged
> 
> I will think about it.

Hey @KiwiKilian ! Thank you for the answer!

To be honest, I disabled any linters that lint the build folder during local development. I think this wasn't quite right. So, personally, I don't need the preview disabling anymore, and I think this issue can be closed. But please do not close the comments on the issue after closing it, as it might still be useful to someone in the future.

**Comment by KiwiKilian** [comment]
If anybody else needs this feel free to chime in with your reasoning. Closing for now.
